{{- $fullname := include "microverse.name" . -}}
{{- $name := .Values.name | default .Release.Name -}}
{{- $chartname := include "microverse.chartname" . -}}
{{- $image := include "microverse.image" . -}}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ $fullname }}
  labels:
    app: {{ $fullname }}
    chart: {{ $chartname }}
    release: {{ $name }}
    heritage: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $fullname }}
      release: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $fullname }}
        release: {{ $name }}
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- range $k, $v := .Values.nodeSelector }}
          {{ $k }}: {{ $v }}
        {{ end -}}
      {{ end }}
      containers:
        - name: {{ $fullname }}
          image: {{ $image }}
          imagePullPolicy: IfNotPresent
          {{- if .Values.env }}
          env:
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: {{ $v }}
            {{ end -}}
          {{ end }}
          ports:
            - name: ice
              containerPort: 3033
              protocol: TCP
            - name: bootstrap
              containerPort: 3040
              protocol: TCP
            - name: dashboard
              containerPort: 3030
              protocol: TCP
            - name: app
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: ice
          readinessProbe:
            httpGet:
              path: /
              port: ice
          resources:
            {}
