{{- $fullname := include "microverse.name" . -}}
{{- $name := .Values.name | default .Release.Name -}}
{{- $chartname := include "microverse.chartname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}
  labels:
    app: {{ $fullname }}
    chart: {{ $chartname }}
    release: {{ $name }}
    heritage: Tiller
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: app
  selector:
    app: {{ $fullname }}
    release: {{ $name }}
---
apiVersion: v1
kind: Service
metadata:
  name: microverse-dashboard-{{ $name }}
  labels:
    app: {{ $fullname }}
    chart: {{ $chartname }}
    release: {{ $name }}
    heritage: Tiller
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3030
    protocol: TCP
    name: dashboard
  selector:
    app: {{ $fullname }}
    release: {{ $name }}
---
apiVersion: v1
kind: Service
metadata:
  name: microverse-ice-{{ $name }}
  labels:
    app: {{ $fullname }}
    chart: {{ $chartname }}
    release: {{ $name }}
    heritage: Tiller
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3033
    protocol: TCP
    name: ice
  selector:
    app: {{ $fullname }}
    release: {{ $name }}
---
apiVersion: v1
kind: Service
metadata:
  name: microverse-bootstrap-{{ $name }}
  labels:
    app: {{ $fullname }}
    chart: {{ $chartname }}
    release: {{ $name }}
    heritage: Tiller
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3040
    protocol: TCP
    name: bootstrap
  selector:
    app: {{ $fullname }}
    release: {{ $name }}
